
spring:
  application:
    name: eureka-server
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      enabled: true
server:
  port: 8761
  address: 0.0.0.0
  
eureka:
  server:
    enable-self-preservation: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #hostname: localhost
    lease-renewal-interval-in-seconds: 10  # Time in seconds for how often the instance renews its lease
    lease-expiration-duration-in-seconds: 30  # Time in seconds for instance expiration when no renewal
    #metadata-map:
      #instanceId: ${spring.application.name}:${random.value}  # Unique instance ID based on the app name and random value
      
logging:
  level:
    '[com.netflix.eureka]': debug
    '[com.netflix.discovery]': debug
